#开发环境配置
spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.119.128:3306/fescar?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useTimezone=true&allowPublicKeyRetrieval=true
    username: admin
    password: Admin1234?
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  redis:
    host:
    password:
    port: 6379
    database: 0
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 10
    timeout: 10000
#开发环境打印sql
logging:
  level:
    com.company.project.biz.mapper: debug
